---
- hosts: all

  tasks:
    - name: update apt cache
      sudo: True
      apt: update_cache=yes

    #
    # The M in MEAN
    #
    - name: import MongoDB public key
      sudo: True
      command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

    - name: add MongoDB repository
      sudo: True
      shell: echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

    - name: install MongoDB
      sudo: True
      apt: name=mongodb-org update-cache=yes

    #
    # The N in MEAN
    #
    - name: add nodesource ppa
      sudo: True
      shell: curl -sL https://deb.nodesource.com/setup_4.x | bash -

    - name: install nodejs
      sudo: True
      apt: name=nodejs state=latest

    - name: update npm to latest
      sudo: True
      npm: name=npm global=yes state=latest
